Add check for user permissions + Bump Discord4j to 3.2.1
HunHage/SlashLib pull request #3
Opened 2022-01-30 07:14 UTC by PgBiel

Adds a new property for commands, "userDiscordPermissions" - basically a PermissionSet for Discord permissions users need to execute this command. E.g. A user should need Kick Members to run a command such as /kick. (Up to the bot's owner to set this, of course).
Also, changed "InteractionCreateEvent" to "DeferrableInteractionEvent"  in InteractionEventReceiverImpl in order to account for Discord4J 3.2.1.
Finally, added a fix (.filter() on InteractionEventReceiverImpl methods) for if someone tries to execute a command the library doesn't know of (used to cause a NullPointerException).

Feel free to suggest any changes.

2022-01-30 23:42 UTC, HunHage requested changes
Small changes for consistency and optimization, all good!

2022-01-30 23:42 UTC, HunHage commented on src/main/java/net/exploitables/slashlib/InteractionEventReceiverImpl.java
> +                .switchIfEmpty(Mono.just(false));
Use `.defaultIfEmpty(false)` instead, this issue existed previously too.

2022-01-30 23:42 UTC, HunHage commented on src/main/java/net/exploitables/slashlib/InteractionEventReceiverImpl.java
> +                .switchIfEmpty(Mono.just(false));
Use `.defaultIfEmpty(false)` instead, this issue existed previously too.

2022-01-30 23:42 UTC, HunHage commented on src/main/java/net/exploitables/slashlib/InteractionEventReceiverImpl.java
> +            // Check bot and user permissions in guild
State `and user` on line 67 in `receiveChatInputInteractionEvent` for consistency

2022-01-30 23:49 UTC, HunHage commented
Thank you for the PR, I didn't add user perm checking since Discord mentioned a slash command permission system that would be customizable by server admins. But that was months ago.

I'm new to GitHub PRs and approvals, let me know if I've made a mistake in the process here.

I'm busy with college at the moment, but I do have some downstream changes to implement. When I get time to merge those I'll release them with this as a new version.

Only other thought is to log a warning when receiving a command that is not known, but I didn't encounter that issue while testing. It is a good change not to error when it happens, and I assume the non-existing interaction would resolve after an hour when the guild updates. Not a necessary change though.

2022-01-31 08:26 UTC, PgBiel commented on src/main/java/net/exploitables/slashlib/InteractionEventReceiverImpl.java
> +            // Check bot and user permissions in guild
I'm pretty sure that was already done - see line 65

2022-01-31 08:36 UTC, PgBiel commented
You're welcome! Don't worry, you did just fine - I've implemented your suggestions.

> I'm busy with college at the moment, but I do have some downstream changes to implement. When I get time to merge those I'll release them with this as a new version.

Alright! Take your time, buddy. If you need any help, let me know.

> Only other thought is to log a warning when receiving a command that is not known

Well, I guess that is possible, I just don't know of a very practical way of adding that with the Reactor API. Maybe with Mono.error()? Not sure...
But feel free to add that later if needed.

Either way, this error should be very rare - just wanted to cover this edge case I found while testing with my bot.

2022-01-31 08:42 UTC, PgBiel commented
Also, sorry for going a bit off-topic here, but I just wanted to mention that I'm preparing a larger pull request to add support for Guild-only Commands!
Most of it is already done, I just need to run some more testing.
Overall though, it seems to be going on a great direction. It will need some reviewing because there are probably going to be design choices you will disagree with - and that is perfectly fine. I believe we can work together to make this possible!

The PR should be up very soon... :)
(At most in the following days!)

2022-01-31 11:01 UTC, HunHage commented on src/main/java/net/exploitables/slashlib/InteractionEventReceiverImpl.java
> +            // Check bot and user permissions in guild
Line 65 says nothing about user permissions, the change to line 67 is to be consistent with this line (82) and line 97

2022-01-31 11:25 UTC, HunHage commented
> Also, sorry for going a bit off-topic here, but I just wanted to mention that I'm preparing a larger pull request to add support for Guild-only Commands! Most of it is already done, I just need to run some more testing. Overall though, it seems to be going on a great direction. It will need some reviewing because there are probably going to be design choices you will disagree with - and that is perfectly fine. I believe we can work together to make this possible!

I gave this a quick look over and do not think I will be able to merge that even with revisions. It has many wild and significant structural changes.

2022-01-31 11:43 UTC, PgBiel commented
> I gave this a quick look over and do not think I will be able to merge that even with revisions. It has many wild and significant structural changes.

Huh... maybe we can discuss this in the PR then?
I know it may seem like a lot at first, but a closer analysis should demonstrate that no breaking changes have been introduced. 
I.e., if you do not use guild-restricted commands, it should feel like nothing changed at all!
I mostly replicated existing structures to account for guild-restricted commands as well, and added a few other structures to support that. 
I'm certain there is margin for improvement, but I really doubt it'd be impossible to merge... especially for such an important feature!

Anyway... but we should be able to discuss this in more detail later, as I should be summing everything up nicely for my PR's description. Feel free, then, to tell me in detail what you think! :)

2022-01-31 11:45 UTC, PgBiel commented
Regarding this specific PR (#3): I think everything should be OK now - if you have any further suggestions, please do tell me! I'll answer ASAP. 👍

2022-01-31 12:44 UTC, PgBiel commented on src/main/java/net/exploitables/slashlib/InteractionEventReceiverImpl.java
> +            // Check bot and user permissions in guild
Uhh... sorry I'm confused
Are you referring to this line?
![image](https://user-images.githubusercontent.com/9021226/151795894-cad3c34d-9322-48fb-9f58-ee639619871a.png)

2022-01-31 12:56 UTC, HunHage commented on src/main/java/net/exploitables/slashlib/InteractionEventReceiverImpl.java
> +            // Check bot and user permissions in guild
It must be a quirk of GH, viewing your branch directly and it is fine as you said. Apologies, all should be good then.

2022-01-31 12:58 UTC, HunHage approved these changes

2022-01-31 13:00 UTC, merged

2022-01-31 13:01 UTC, PgBiel commented on src/main/java/net/exploitables/slashlib/InteractionEventReceiverImpl.java
> +            // Check bot and user permissions in guild
Don't worry, it's perfectly fine 👍

2022-02-06 16:38 UTC, HunHage commented
I made a mistake and did not reproduce this issue locally, and am unable to using the previous build. Can you provide reproduction steps or a working example?

2022-02-06 17:33 UTC, PgBiel commented
> I made a mistake and did not reproduce this issue locally, and am unable to using the previous build. Can you provide reproduction steps or a working example?

Refer to https://github.com/HunHage/SlashLib/pull/4#discussion_r800209456

2022-02-06 19:42 UTC, HunHage commented
Ok, so since this is an organizational nightmare at this point I'll quote.

HunHage:
> I have been unable to reproduce a situation where the library receives a command it did not register when registerCommands has been properly called. This also means I made a mistake and merged https://github.com/HunHage/SlashLib/pull/3 without replicating the issue. Handling state that is changed outside of SlashLib is outside of scope for the library. When registering commands Discord should be 100% updated with the proper state and we should not be receiving commands we don't know about.

>I do not understand under what circumstances the library receives a command it didn't create/modify/delete with registerCommands, as when a command is deleted Discord does not provide an event to the bot when it is called since it's ID is invalid.

PgBiel:
> It should only happen when guild-only commands are involved. This happened to me because I had pre-registered guild-only commands from before (and I hadn't noticed), and when they were run (in the master branch - not the branch with this PR), it resulted in a NullPointerException, because the master build doesn't check for guild-only commands.
Hence the fallback - simply do not reply in this case, as it wouldn't concern the library. (Although we can surely add a log warn for this.)

This makes no sense, SlashLib cannot account for modifications made to interactions outside of itself. There are far too many ways that an improper state can be made which will cause the library to encounter errors. The supported use-case is that SlashLib is used to manage interactions, altering interactions outside the library invalidates the state of SlashLib and leads to errors. The desired state is that SlashLib knows about **all** interactions and handles them accordingly. If it does not then there is an error. Since SlashLib doesn't support guild interactions then there should be no guild interactions.

This is against the design of the library, the state of interactions is supposed to be known. Trying to compensate for interaction systems outside this library goes against the point of using it as it is not *designed* to work with other/custom interaction frameworks. I understand that SlashLib doesn't support guild commands but it makes no sense to try and allow multiple solutions to manage interactions when SlashLib is supposed to be *the* solution.

I'm pulling the plug on this, my mistake for approving it as I did, but I am beginning to bleed time trying to handle this retroactive communication and account for changes that will be redundant when proper support exists. I will update the methods for PRs and Issues to be opened for the future.

2022-02-06 20:18 UTC, HunHage commented
Reverted manually with
8ac412ce66ad64abaebb378388f7c4c7606a3339
dbdb66df79b391dc6dd4da364e78cca658644338
39bfdb241c11634506d8bc21e4d3811ec7cedfbd
ca092387c14e68a98c39a6a0a94f53ace46c4473
d5900a743cae64c01a78ce8af6542f3f6e82f1cd

I should have time this weekend to merge downstream changes I don't have on github, and will update the D4J version and implement new features after validating the downstream behavior with them.

2022-02-06 21:20 UTC, PgBiel commented
Alright. I am terribly sorry that my contributions weren't appropriate for the design you intend for the library. I will make sure to avoid bringing any further such inconvenience to you in the future. My apologies once again for any trouble caused, and have a great day!